/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestEIP1271Signer } from "./TestEIP1271Signer";
export type { TestEIP1271Verifier } from "./TestEIP1271Verifier";
