/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    isRegistered: boolean;
    creditScore: BigNumberish;
    easAttestationUID: string;
    isWhitelisted: boolean;
    lastUpdated: BigNumberish;
  };

  export type AgentStructOutput = [
    isRegistered: boolean,
    creditScore: bigint,
    easAttestationUID: string,
    isWhitelisted: boolean,
    lastUpdated: bigint
  ] & {
    isRegistered: boolean;
    creditScore: bigint;
    easAttestationUID: string;
    isWhitelisted: boolean;
    lastUpdated: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WHITELIST_THRESHOLD"
      | "agents"
      | "getAgent"
      | "getRegisteredAgents"
      | "owner"
      | "registerAgent"
      | "registeredAgents"
      | "renounceOwnership"
      | "reputationNFT"
      | "setWhitelisted"
      | "totalAgents"
      | "transferOwnership"
      | "updateCreditScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "CreditScoreUpdated"
      | "OwnershipTransferred"
      | "WhitelistStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "WHITELIST_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredAgents",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registeredAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelisted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreditScore",
    values: [AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "WHITELIST_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreditScore",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditScoreUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    newScore: BigNumberish,
    easUID: string
  ];
  export type OutputTuple = [agent: string, newScore: bigint, easUID: string];
  export interface OutputObject {
    agent: string;
    newScore: bigint;
    easUID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistStatusChangedEvent {
  export type InputTuple = [agent: AddressLike, status: boolean];
  export type OutputTuple = [agent: string, status: boolean];
  export interface OutputObject {
    agent: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WHITELIST_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, string, boolean, bigint] & {
        isRegistered: boolean;
        creditScore: bigint;
        easAttestationUID: string;
        isWhitelisted: boolean;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  getAgent: TypedContractMethod<
    [agent: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getRegisteredAgents: TypedContractMethod<[], [string[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<[], [void], "nonpayable">;

  registeredAgents: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationNFT: TypedContractMethod<[], [string], "view">;

  setWhitelisted: TypedContractMethod<
    [agent: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCreditScore: TypedContractMethod<
    [agent: AddressLike, score: BigNumberish, easUID: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WHITELIST_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, string, boolean, bigint] & {
        isRegistered: boolean;
        creditScore: bigint;
        easAttestationUID: string;
        isWhitelisted: boolean;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agent: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredAgents"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setWhitelisted"
  ): TypedContractMethod<
    [agent: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCreditScore"
  ): TypedContractMethod<
    [agent: AddressLike, score: BigNumberish, easUID: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreditScoreUpdated"
  ): TypedContractEvent<
    CreditScoreUpdatedEvent.InputTuple,
    CreditScoreUpdatedEvent.OutputTuple,
    CreditScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistStatusChanged"
  ): TypedContractEvent<
    WhitelistStatusChangedEvent.InputTuple,
    WhitelistStatusChangedEvent.OutputTuple,
    WhitelistStatusChangedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "CreditScoreUpdated(address,uint256,string)": TypedContractEvent<
      CreditScoreUpdatedEvent.InputTuple,
      CreditScoreUpdatedEvent.OutputTuple,
      CreditScoreUpdatedEvent.OutputObject
    >;
    CreditScoreUpdated: TypedContractEvent<
      CreditScoreUpdatedEvent.InputTuple,
      CreditScoreUpdatedEvent.OutputTuple,
      CreditScoreUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WhitelistStatusChanged(address,bool)": TypedContractEvent<
      WhitelistStatusChangedEvent.InputTuple,
      WhitelistStatusChangedEvent.OutputTuple,
      WhitelistStatusChangedEvent.OutputObject
    >;
    WhitelistStatusChanged: TypedContractEvent<
      WhitelistStatusChangedEvent.InputTuple,
      WhitelistStatusChangedEvent.OutputTuple,
      WhitelistStatusChangedEvent.OutputObject
    >;
  };
}
