/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestEIP1271Signer__factory } from "./TestEIP1271Signer__factory";
export { TestEIP1271Verifier__factory } from "./TestEIP1271Verifier__factory";
