/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  TestEIP1271Signer,
  TestEIP1271SignerInterface,
} from "../../../../../contracts/eas/tests/eip1271/TestEIP1271Signer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "magicValue",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "mockSignature",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b5061039b8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c80631626ba7e14610038578063ba9d2acb14610068575b5f5ffd5b61004b61004636600461018d565b61007d565b6040516001600160e01b0319909116815260200160405180910390f35b61007b61007636600461018d565b61016f565b005b5f838152602081905260408120805482919061009890610204565b80601f01602080910402602001604051908101604052809291908181526020018280546100c490610204565b801561010f5780601f106100e65761010080835404028352916020019161010f565b820191905f5260205f20905b8154815290600101906020018083116100f257829003601f168201915b505050505090508383905081511480156101465750838360405161013492919061023c565b60405180910390208180519060200120145b1561015b5750630b135d3f60e11b9050610168565b506001600160e01b031990505b9392505050565b5f8381526020819052604090206101878284836102ab565b50505050565b5f5f5f6040848603121561019f575f5ffd5b83359250602084013567ffffffffffffffff8111156101bc575f5ffd5b8401601f810186136101cc575f5ffd5b803567ffffffffffffffff8111156101e2575f5ffd5b8660208284010111156101f3575f5ffd5b939660209190910195509293505050565b600181811c9082168061021857607f821691505b60208210810361023657634e487b7160e01b5f52602260045260245ffd5b50919050565b818382375f9101908152919050565b634e487b7160e01b5f52604160045260245ffd5b601f8211156102a657805f5260205f20601f840160051c810160208510156102845750805b601f840160051c820191505b818110156102a3575f8155600101610290565b50505b505050565b67ffffffffffffffff8311156102c3576102c361024b565b6102d7836102d18354610204565b8361025f565b5f601f841160018114610308575f85156102f15750838201355b5f19600387901b1c1916600186901b1783556102a3565b5f83815260208120601f198716915b828110156103375786850135825560209485019460019092019101610317565b5086821015610353575f1960f88860031b161c19848701351681555b505060018560011b018355505050505056fea26469706673582212200055c6fed0594935acb984ffec7d40511b4f3f24cb2523222b3ca814d6ffcbbb64736f6c634300081c0033";

type TestEIP1271SignerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestEIP1271SignerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestEIP1271Signer__factory extends ContractFactory {
  constructor(...args: TestEIP1271SignerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestEIP1271Signer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TestEIP1271Signer__factory {
    return super.connect(runner) as TestEIP1271Signer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestEIP1271SignerInterface {
    return new Interface(_abi) as TestEIP1271SignerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestEIP1271Signer {
    return new Contract(address, _abi, runner) as unknown as TestEIP1271Signer;
  }
}
