/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as examples from "./examples";
export type { examples };
export type { ISchemaResolver } from "./ISchemaResolver";
export type { SchemaResolver } from "./SchemaResolver";
